# action.yml
name: 'Run Jupyter Notebook'
description: 'Run a Jupyter Notebook to test MAAP services'
inputs:
  stage:
    description: Stage / environment on which the tests will be invoked
    required: true
runs:
  using: 'docker'
  # replace with 'Dockerfile' to build when action is run
  image: 'ghcr.io/maap-project/maap-data-system-tests:main'
  args:
    - ${{ inputs.stage }}
