# action.yml
name: 'Run Jupyter Notebook'
description: 'Run a Jupyter Notebook to test MAAP services'
inputs:
  stage:
    description: Stage / environment on which the tests will be invoked
    required: true
# outputs:
  # output_1: # id of output
    # description: 'The result'
runs:
  using: 'docker'
  image: 'ghcr.io/maap-project/maap-data-system-tests:pr-11' # todo: main?
  args:
    - ${{ inputs.stage }}
