name: System Tests
on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:
      inputs:
        name:
          description: 'Stage'
          required: true
          default: 'production'
  schedule:
   - cron:  '43 3 * * *' # daily
  pull_request:
    branches:
      - main

# env:

jobs:
  system-test:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/checkout@v2

      - name: Run the tests
        uses: ./
        id: test_run
        with:
          stage: ${{ steps.extract_branch.outputs.branch }}

      # Use the output from the test run step
      # - name: Get the output
        # run: echo "The time was ${{ steps.test_run.outputs.output_1 }}"