name: System Tests
on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:
      inputs:
        name:
          description: 'Stage'
          required: true
          default: 'production'
  schedule:
   - cron:  '0 0 * * *' # daily
  pull_request:
    branches:
      - main

# env:

jobs:
  system-test:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/checkout@v2

      # - uses: franzbischoff/replace_envs@v1
      #   env:
      #     STAGE: ${{ steps.extract_branch.outputs.branch }}
      #   with:
      #     from_file: 'stack/config.yml.example'
      #     to_file: 'stack/config.yml'
      #     commit: 'false'

      # To use this repository's private action,
      # you must check out the repository
      - name: Run the tests
        uses: ./
        id: test_run
        # with:
          # arg_1: 'Bar'
      # Use the output from the test run step
      # - name: Get the output
        # run: echo "The time was ${{ steps.test_run.outputs.output_1 }}"